import json
import subprocess
import sys

THEME_ID = "gid://shopify/OnlineStoreTheme/139682218059"
STORE = "3rnv2d-i3.myshopify.com"

template = {
  "sections": {
    "main": {
      "type": "main-product",
      "blocks": {
        "title": {
          "type": "title",
          "settings": {
            "text_size": "h2",
            "title_alignment": "left",
            "uppercase_title": False,
            "margin_top": 9,
            "margin_bottom": 3
          }
        },
        "a6eb81db-40e4-43e0-972f-32db010a4a56": {
          "type": "rating_stars",
          "settings": {
            "rating": 4.9,
            "star_color": "#ffcc00",
            "bg_stars_style": "full",
            "bg_star_color": "#ececec",
            "label": "<strong>4.9 | 15,000+ Happy Customers</strong>",
            "size": 13,
            "alignment": "flex-start",
            "scroll_id": "",
            "margin_top": 9,
            "margin_bottom": 9
          }
        },
        "text_4ne6gk": {
          "type": "text",
          "settings": {
            "mobile_text_size": 14,
            "desktop_text_size": 16,
            "alignment": "left",
            "text_color": "#121212",
            "text_1": "<strong>Supports nerve comfort — calms tingling, burning &amp; sensitivity</strong>",
            "text_2": "<strong>Universal antioxidant — protects nerves from oxidative stress</strong>",
            "text_3": "<strong>Supports mitochondrial energy, blood sugar &amp; healthy aging</strong>",
            "icon_scale": 120,
            "icon_color": "#264165",
            "icon_1": "check_circle",
            "filled_icon_1": True,
            "icon_2": "check_circle",
            "filled_icon_2": True,
            "icon_3": "check_circle",
            "filled_icon_3": True,
            "width": "100%",
            "direction": "vertical",
            "column_gap": 3,
            "enable_bg": False,
            "bg_color": "#f3f3f3",
            "corner_radius": 40,
            "padding": 3,
            "border_size": 0,
            "border_color": "#b7b7b7",
            "margin_top": 15,
            "margin_bottom": 9
          }
        },
        "text_EamU3e": {
          "type": "text",
          "disabled": True,
          "settings": {
            "mobile_text_size": 14,
            "desktop_text_size": 16,
            "alignment": "left",
            "text_color": "#121212",
            "text_1": "<strong>Gentle on the stomach — take with food for best results</strong>",
            "text_2": "<strong>Pure R-Form ALA — the naturally active form your body recognizes</strong>",
            "text_3": "",
            "icon_scale": 120,
            "icon_color": "#264165",
            "icon_1": "check_circle",
            "filled_icon_1": True,
            "icon_2": "check_circle",
            "filled_icon_2": True,
            "icon_3": "check_circle",
            "filled_icon_3": True,
            "width": "100%",
            "direction": "vertical",
            "column_gap": 3,
            "enable_bg": False,
            "bg_color": "#f3f3f3",
            "corner_radius": 40,
            "padding": 3,
            "border_size": 0,
            "border_color": "#b7b7b7",
            "margin_top": 0,
            "margin_bottom": 0
          }
        },
        "5fcc0428-e768-4cb7-bea3-eb0274198dd1": {
          "type": "variant_picker",
          "settings": {
            "picker_types": "pills, dropdown, dropdown",
            "custom_labels": "[name] - [selected]",
            "skip_unavailable": False,
            "swatches_size": "medium",
            "swatches_custom_colors": "disabled",
            "swatches_custom_colors_list": "#000000, #264165, #0000FF, #FFCC00",
            "full_width_dropdowns": False,
            "breaks_style": "normal",
            "breaks_headline": "BUNDLE & SAVE",
            "breaks_display_selected_indicator": True,
            "breaks_border_radius": 10,
            "breaks_border_width": 2,
            "breaks_color_scheme": "accent-1",
            "breaks_badges": "[empty], Most popular, [empty]",
            "breaks_badge_style": "1",
            "breaks_badge_color": "accent-1",
            "breaks_displayed_images": "variant_images",
            "breaks_custom_images": "",
            "breaks_image_width": 70,
            "breaks_space_images": True,
            "breaks_vertical_images_position": "top",
            "breaks_vertical_prices_layout": "vertical",
            "breaks_labels": "[name], [name], [name]",
            "breaks_benefits": "[empty], Free Shipping, Free Shipping",
            "breaks_benefit_position": "top",
            "breaks_benefit_style": "outlined",
            "breaks_benefit_color": "accent-1",
            "breaks_captions": "Variant 1 caption, Variant 2 caption, Variant 3 caption",
            "breaks_price_texts": "[price], [price], [price]",
            "breaks_compare_price_texts": "[compare_price], [compare_price], [compare_price]",
            "margin_top": 15,
            "margin_bottom": 15
          }
        },
        "text_bctCLi": {
          "type": "text",
          "settings": {
            "mobile_text_size": 14,
            "desktop_text_size": 14,
            "alignment": "center",
            "text_color": "#555555",
            "text_1": "✓  <strong>60-Day Money-Back Guarantee</strong>",
            "text_2": "",
            "text_3": "",
            "icon_scale": 120,
            "icon_color": "#264165",
            "icon_1": "",
            "filled_icon_1": False,
            "icon_2": "",
            "filled_icon_2": False,
            "icon_3": "",
            "filled_icon_3": False,
            "width": "100%",
            "direction": "vertical",
            "column_gap": 1,
            "enable_bg": False,
            "bg_color": "#f3f3f3",
            "corner_radius": 40,
            "padding": 3,
            "border_size": 0,
            "border_color": "#b7b7b7",
            "margin_top": 9,
            "margin_bottom": 0
          }
        },
        "buy_buttons": {
          "type": "buy_buttons",
          "settings": {
            "show_dynamic_checkout": False,
            "skip_cart": False,
            "uppercase_text": True,
            "icon_scale": 120,
            "icon_spacing": 10,
            "display_price": False,
            "enable_custom_color": False,
            "custom_color": "#264165",
            "enable_secondary_btn": False,
            "secondary_btn_label": "Buy It Now",
            "secondary_btn_enable_custom_color": False,
            "secondary_btn_custom_color": "#264165",
            "margin_top": 9,
            "margin_bottom": 24
          }
        },
        "review_avatars_9gqG4t": {
          "type": "review_avatars",
          "settings": {
            "alignment": "center",
            "corner_radius": 6,
            "avatars_position": "left",
            "avatar_size": 40,
            "avatar_offset": -10,
            "checkmark_color": "#264165",
            "checkmark_icon_color": "#ffffff",
            "checkmark_size": 20,
            "star_color": "#ffcc00",
            "stars_translate": 0,
            "stars_scroll_id": "",
            "avatar_1_verified": False,
            "avatar_2_verified": False,
            "avatar_3_verified": False,
            "avatar_4_verified": False,
            "avatar_5_verified": False,
            "text_1_line_1": "Beware of Amazon fakes! Romira R-Alpha Lipoic Acid is exclusively sold here on our website",
            "text_1_line_1_size": 14,
            "text_1_line_2": "",
            "text_1_line_2_size": 12,
            "text_1_color": "#ff0000",
            "text_1_bg_color": "#ffc2c2",
            "text_1_border_size": 0,
            "text_1_border_color": "#ae2d3e",
            "text_1_offset": -30,
            "text_1_padding_y": 4,
            "text_1_padding_x": 14,
            "text_1_stretch_height": True,
            "text_2_line_1": "",
            "text_2_line_1_size": 14,
            "text_2_line_2": "",
            "text_2_line_2_size": 12,
            "text_2_color": "#221212",
            "text_2_bg_color": "#ffffff",
            "text_2_border_size": 0,
            "text_2_border_color": "#b7b7b7",
            "text_2_offset": -14,
            "text_2_padding_y": 4,
            "text_2_padding_x": 14,
            "text_2_stretch_height": True,
            "margin_top": 15,
            "margin_bottom": 15
          }
        },
        "reviews_gtkAkf": {
          "type": "reviews",
          "settings": {
            "color_scheme": "background-2",
            "show_custom_bg": True,
            "custom_bg_color": "#f6f5f1",
            "corner_radius": 16,
            "border_width": 0,
            "border_color": "#f6f5f1",
            "avatar_alignment": "top",
            "avatar_corner_radius": 40,
            "star_color": "#ffcc00",
            "stars_translate": 0,
            "checkmark_color": "#264165",
            "checkmark_icon_color": "#ffffff",
            "slider_type": "slide",
            "autoplay": False,
            "autoplay_speed": 6,
            "display_arrows": True,
            "display_dots": False,
            "author_1": "Dr. Rachel Morgan, PhD – Nutritional Neuroscience Researcher [stars]",
            "image_1": "shopify://shop_images/ChatGPT_Image_Oct_7_2025_02_26_11_AM.png",
            "text_1": "<p>\"R-Alpha Lipoic Acid is one of the most remarkable antioxidant compounds studied in nerve health research. What makes it exceptional is its <strong>dual water and fat solubility</strong> — it protects nerve cells both inside and outside the membrane. The R-form is the naturally occurring enantiomer and the one most closely aligned with how the body actually uses ALA.\"</p>",
            "author_2": "Patricia M. | Age: 61 [stars]",
            "image_2": "shopify://shop_images/gempages_587632787746456096-33fca131-f4a3-4c51-a099-d0ff00d27fa6.png",
            "text_2": "<p>\"The burning and tingling in my feet had been going on for years — worst at night. After <strong>about four weeks</strong> on Romira R-ALA, the nighttime irritation started calming down. By week six I was <strong>sleeping through the night again</strong> for the first time in years.\"</p>",
            "author_3": "Alan M. | Age: 63 [stars]",
            "image_3": "shopify://shop_images/Untitled_design_22.png",
            "text_3": "<p>\"I tried CBD, magnesium, turmeric — nothing really addressed the nerve sensitivity in my legs. This is different. It’s <strong>cleaner, more consistent</strong>, and the discomfort has genuinely <strong>dialled down the longer I take it</strong>. On my second bottle now.\"</p>",
            "margin_top": 12,
            "margin_bottom": 24
          }
        },
        "e0a0b690-50df-4ca4-acfd-ce2980696cce": {
          "type": "shipping_checkpoints",
          "settings": {
            "icon_1": "add_shopping_cart",
            "filled_icon_1": False,
            "top_text_1": "<strong>[start_date]</strong>",
            "bottom_text_1": "Ordered",
            "min_days_1": 0,
            "max_days_1": 0,
            "icon_2": "local_shipping",
            "filled_icon_2": False,
            "top_text_2": "<strong>[start_date] - [end_date]</strong>",
            "bottom_text_2": "Order Ready",
            "min_days_2": 1,
            "max_days_2": 2,
            "icon_3": "redeem",
            "filled_icon_3": False,
            "top_text_3": "<strong>[start_date] - [end_date]</strong>",
            "bottom_text_3": "Delivered",
            "min_days_3": 8,
            "max_days_3": 10,
            "icon_4": "",
            "filled_icon_4": False,
            "top_text_4": "",
            "bottom_text_4": "",
            "date_format": "mm_dd",
            "days_labels": "Mon, Tue, Wed, Thu, Fri, Sat, Sun",
            "months_labels": "Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec",
            "color_scheme": "accent-1",
            "margin_top": 24,
            "margin_bottom": 24
          }
        },
        "e7a28cbe-03cb-4c9d-a2c4-0e3e76ffb3e5": {
          "type": "sticky_atc",
          "settings": {
            "function": "add_to_cart",
            "display_when": "after_scroll",
            "button_label": "Add to cart",
            "enable_custom_btn_color": False,
            "custom_btn_color": "#264165",
            "color_scheme": "background-1",
            "star_color": "#ffcc00",
            "stars_label": "(xxxx Reviews)",
            "picker_type": "combined",
            "desktop_show_image": True,
            "desktop_show_title": True,
            "desktop_rating_stars": False,
            "desktop_show_price": True,
            "desktop_show_sale_badge": True,
            "desktop_variant_picker": True,
            "desktop_full_button_width": False,
            "desktop_show_price_in_button": False,
            "desktop_transparent_bg": False,
            "mobile_show_image": False,
            "mobile_show_title": True,
            "mobile_rating_stars": False,
            "mobile_show_price": True,
            "mobile_show_sale_badge": False,
            "mobile_variant_picker": False,
            "mobile_full_button_width": False,
            "mobile_show_price_in_button": False,
            "mobile_transparent_bg": False
          }
        },
        "de158e68-5d0d-4819-a625-e2dabdff87d1": {
          "type": "collapsible_tab",
          "settings": {
            "heading": "The Science Behind It",
            "heading_size": "large",
            "icon": "",
            "filled_icon": False,
            "collapse_icon": "carret",
            "display_top_border": True,
            "open": False,
            "content": "<p>R-Alpha Lipoic Acid — known as R-ALA — is the naturally occurring form of alpha-lipoic acid, a compound your body already produces in every cell to support energy production inside the mitochondria.</p><p>What makes R-ALA exceptional is its <strong>dual solubility</strong>: unlike most antioxidants that work only in water-based or fat-based environments, R-ALA functions in both. This means it can protect nerve cells both inside and outside the cell membrane — an advantage sometimes called the “universal antioxidant” quality. No other single antioxidant covers as much ground.</p><p>R-ALA supports nerve health through several important pathways. It directly <strong>neutralizes free radicals and reactive oxygen species</strong> that can irritate and damage nerve tissue. It <strong>supports mitochondrial energy metabolism</strong> — nerve cells are energy-hungry, and healthy mitochondrial function is essential for normal nerve signalling. It supports <strong>healthy glucose metabolism</strong>, which is closely connected to long-term nerve wellness. And critically, it <strong>regenerates other antioxidants</strong> including Vitamin C, Vitamin E, and Glutathione — amplifying the body’s entire antioxidant network.</p><p>R-ALA is the biologically active enantiomer — the form the body recognizes and uses. Standard alpha-lipoic acid supplements often contain a 50/50 racemic mixture of R and S forms. The S-form is synthetic and not found in nature. By using the pure R-form, Romira ensures you are getting the version most closely aligned with how the body is designed to work.</p><p>600mg is the most widely used daily serving in clinical and wellness settings for nerve comfort and antioxidant support.</p>",
            "page": "",
            "margin_top": 24,
            "margin_bottom": 0
          }
        },
        "collapsible_tab_LPNzCP": {
          "type": "collapsible_tab",
          "settings": {
            "heading": "Is It Safe?",
            "heading_size": "large",
            "icon": "",
            "filled_icon": False,
            "collapse_icon": "carret",
            "display_top_border": True,
            "open": False,
            "content": "<p>Yes. Alpha-lipoic acid has been used in clinical and wellness settings for decades and is generally considered safe for adult use. R-ALA in particular is well tolerated because it is the naturally occurring form already present in the body in small amounts.</p><p>Romira R-Alpha Lipoic Acid is <strong>100% natural, non-GMO, vegan</strong>, and made without artificial fillers, binders, or preservatives. Every batch is <strong>third-party tested for purity and potency</strong> and produced in a <strong>GMP-certified facility in the USA</strong>.</p><p><strong>Free from:</strong> Gluten, Soy, Eggs, Dairy, Nuts, Preservatives, and Animal Products.</p><p>The most commonly noted side effect is mild nausea in a small number of users, particularly on an empty stomach. Taking capsules with food — ideally containing some healthy fat — reduces this and also improves absorption since R-ALA is fat-soluble. If you are managing blood sugar or taking diabetes medication, consult your healthcare provider before use, as ALA supports glucose metabolism. If you are pregnant, nursing, or taking prescription medication, please consult your doctor before use.</p>",
            "page": "",
            "margin_top": 24,
            "margin_bottom": 0
          }
        },
        "collapsible_tab_ccfrML": {
          "type": "collapsible_tab",
          "settings": {
            "heading": "Ingredients",
            "heading_size": "large",
            "icon": "",
            "filled_icon": False,
            "collapse_icon": "carret",
            "display_top_border": True,
            "open": False,
            "content": "<p>Each daily serving (2 veggie capsules) contains:</p><p><strong>600mg R-Alpha Lipoic Acid</strong><br/>The naturally active R-form — the version your body recognizes and uses most efficiently. Not a racemic (50/50 R/S) mixture.</p><p><strong>Organic Coconut Oil</strong><br/>Included because R-ALA is fat-soluble. Pairing it with Organic Coconut Oil in each capsule supports proper absorption — so the dose you take is the dose your body actually gets to use.</p><p><strong>Other Ingredients:</strong> Vegetable cellulose (capsule shell). Nothing else.</p><p><strong>Free from:</strong> Gluten, Soy, Eggs, Dairy, Nuts, Preservatives, Animal Products</p><p><strong>Made in the USA</strong> — GMP Certified, Third-Party Lab Tested</p><p><strong>No fillers. No binders. No synthetic additives. Pure R-ALA in the form your body actually uses.</strong></p>",
            "page": "",
            "margin_top": 24,
            "margin_bottom": 0
          }
        },
        "collapsible_tab_WVx44p": {
          "type": "collapsible_tab",
          "settings": {
            "heading": "60-Day Guarantee",
            "heading_size": "large",
            "icon": "",
            "filled_icon": False,
            "collapse_icon": "carret",
            "display_top_border": True,
            "open": False,
            "content": "<p>We offer a <strong>60-day money-back guarantee</strong> — because R-ALA works cumulatively, and we want you to have the full evaluation window to experience what consistent daily use can do.</p><p>If for any reason you are not completely satisfied after completing your 60-day protocol, we will issue a <strong>full refund, no questions asked</strong>. Simply contact our support team and we will take care of you.</p>",
            "page": "",
            "margin_top": 24,
            "margin_bottom": 0
          }
        }
      },
      "block_order": [
        "title",
        "a6eb81db-40e4-43e0-972f-32db010a4a56",
        "text_4ne6gk",
        "text_EamU3e",
        "5fcc0428-e768-4cb7-bea3-eb0274198dd1",
        "text_bctCLi",
        "buy_buttons",
        "review_avatars_9gqG4t",
        "reviews_gtkAkf",
        "e0a0b690-50df-4ca4-acfd-ce2980696cce",
        "e7a28cbe-03cb-4c9d-a2c4-0e3e76ffb3e5",
        "de158e68-5d0d-4819-a625-e2dabdff87d1",
        "collapsible_tab_LPNzCP",
        "collapsible_tab_ccfrML",
        "collapsible_tab_WVx44p"
      ],
      "custom_css": [],
      "settings": {
        "display_id": False,
        "enable_sticky_info": True,
        "display_variant_image_first": False,
        "disable_prepend": True,
        "hide_variants": False,
        "variant_image_filtering": "none",
        "image_zoom": "none",
        "thumbnails_ratio": "original",
        "arrows_color_scheme": "inverse",
        "transparent_arrows": False,
        "dots_color_scheme": "inverse",
        "video_player": "play_btn",
        "enable_video_looping": False,
        "autoplay_videos_pause_btn": False,
        "video_sound_btn": False,
        "video_timeline": False,
        "play_btn_color_scheme": "accent-1",
        "sound_btn_color_scheme": "inverse",
        "timeline_color": "accent-1",
        "media_size": "medium",
        "media_position": "left",
        "gallery_layout": "thumbnail_slider",
        "desktop_thumbnails_position": "bottom",
        "desktop_thumbnails_count": 5,
        "desktop_vertical_thumbnails_width": 16,
        "desktop_vertical_thumbnails_hide_arrows": False,
        "constrain_to_viewport": True,
        "media_fit": "contain",
        "desktop_arrows_position": "hidden",
        "mobile_media_corner_radius": 0,
        "mobile_spacing_pixels": 0,
        "mobile_arrows_position": "sides",
        "mobile_pagination": "hidden",
        "mobile_thumbnails_position": "hidden",
        "mobile_thumbnails_count": 5,
        "mobile_vertical_thumbnails_width": 22,
        "mobile_vertical_thumbnails_hide_arrows": True,
        "mobile_scroll_padding_percentage": 0,
        "mobile_scroll_padding_pixels": 0,
        "enable_mobile_outher_spacing": False,
        "mobile_slides_container_width": 100,
        "mobile_slides_inner_width": 100,
        "trust_badge_position": "top-right",
        "trust_badge_size": "medium",
        "mobile_padding_top": 0,
        "mobile_padding_bottom": 0,
        "desktop_padding_top": 12,
        "desktop_padding_bottom": 36
      }
    },
    "related-products": {
      "type": "related-products",
      "disabled": True,
      "settings": {
        "display_id": False,
        "title": "You may also like",
        "title_highlight_color": "#264165",
        "heading_size": "h2",
        "products_to_show": 4,
        "columns_desktop": 4,
        "color_scheme": "background-1",
        "image_ratio": "adapt",
        "show_secondary_image": False,
        "show_vendor": False,
        "show_rating": False,
        "enable_quick_add": False,
        "columns_mobile": "2",
        "padding_top": 36,
        "padding_bottom": 24
      }
    },
    "ss_video_with_text_3_qiaRVV": {
      "type": "ss-video-with-text-3",
      "name": "SS - Video with Text #3",
      "settings": {
        "media": "image",
        "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_42_52_AM.png",
        "video_url": "",
        "media_width": 50,
        "media_width_mobile": 100,
        "media_position": "second",
        "media_position_mobile": "second",
        "media_ratio": "original",
        "media_ratio_mobile": "original",
        "media_border_thickness": 0,
        "media_radius": 0,
        "controls": False,
        "autoplay": True,
        "loop": True,
        "content_padding_vertical": 32,
        "content_padding_vertical_mobile": 40,
        "content_padding_horizontal": 100,
        "content_padding_horizontal_mobile": 12,
        "heading": "<h2><strong>One Form. Chosen For a Reason.</strong></h2>",
        "heading_custom": False,
        "heading_font": "josefin_sans_n4",
        "heading_size": 50,
        "heading_size_mobile": 36,
        "heading_height": 110,
        "heading_align": "left",
        "heading_align_mobile": "center",
        "heading_position": "1",
        "heading_position_mobile": "1",
        "sub_heading": "<h3><strong>Romira R-ALA uses the pure R-form of alpha-lipoic acid — and that is a deliberate choice. Standard ALA supplements contain a 50/50 mixture of R and S forms. The S-form is synthetic and not found in nature. The R-form is the naturally occurring, biologically active version — the one your body recognizes, absorbs, and uses most efficiently. Paired with Organic Coconut Oil for optimal absorption. 600mg per serving.</strong></h3>",
        "sub_heading_custom": False,
        "sub_heading_font": "josefin_sans_n4",
        "sub_heading_size": 18,
        "sub_heading_size_mobile": 18,
        "sub_heading_height": 150,
        "sub_heading_align": "left",
        "sub_heading_align_mobile": "center",
        "sub_heading_mt": 40,
        "sub_heading_position": "2",
        "sub_heading_position_mobile": "4",
        "text": "",
        "text_custom": False,
        "text_font": "josefin_sans_n4",
        "text_size": 18,
        "text_size_mobile": 18,
        "text_height": 150,
        "text_align": "left",
        "text_align_mobile": "center",
        "text_mt": 40,
        "text_position": "2",
        "text_position_mobile": "4",
        "button": "",
        "button_url": "",
        "button_custom": False,
        "button_font": "josefin_sans_n4",
        "button_size": 18,
        "button_size_mobile": 18,
        "button_height": 100,
        "button_align": "left",
        "button_align_mobile": "center",
        "button_mt": 32,
        "button_padding_vertical": 16,
        "button_padding_vertical_mobile": 16,
        "button_padding_horizontal": 26,
        "button_padding_horizontal_mobile": 26,
        "button_radius": 32,
        "button_border_thickness": 0,
        "button_use_arrow": True,
        "button_position": "4",
        "button_position_mobile": "3",
        "button_color": "#ffffff",
        "button_hover_color": "#ffffff",
        "button_bg_color": "#264165",
        "button_bg_hover_color": "#1a2e47",
        "button_border_color": "#000000",
        "button_border_hover_color": "#000000",
        "media_border_color": "#000000",
        "heading_color": "#000000",
        "sub_heading_color": "#000000",
        "text_color": "#000000",
        "background_color": "#ffffff",
        "background_gradient": "",
        "border_color": "#000000",
        "margin_top": 0,
        "margin_bottom": 0,
        "padding_top": 0,
        "padding_bottom": 0,
        "padding_horizontal": 0,
        "padding_horizontal_mobile": 0,
        "full_width": True,
        "content_width": 120,
        "border_thickness": 0,
        "lazy": True
      }
    },
    "ss_testimonial_12_aKxHaF": {
      "type": "ss-testimonial-12",
      "blocks": {
        "slide_1": {
          "type": "slide",
          "settings": {
            "media_style": "image",
            "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_38_13_AM.png",
            "video_url": "",
            "controls": False,
            "stars_count": 5,
            "text": "<p>\"The burning and tingling in my feet had been going on for years — worst at night when I was trying to sleep. By week four on Romira R-ALA the nighttime irritation had genuinely calmed. By week six I was sleeping through the night again. Cannot recommend it enough.\"</p>",
            "author": "<p><strong>Helen P.</strong> — Age 64, Verified Customer</p>"
          }
        },
        "slide_2": {
          "type": "slide",
          "settings": {
            "media_style": "image",
            "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_38_06_AM.png",
            "video_url": "",
            "controls": False,
            "stars_count": 5,
            "text": "<p>\"I tried CBD, magnesium, turmeric — nothing consistently addressed the pins and needles I get in my hands and feet. This is different. The tingling has dialled down noticeably and I feel sharper overall. About eight weeks in and I have no plans to stop.\"</p>",
            "author": "<p><strong>Diane C.</strong> — Age 57, Verified Customer</p>"
          }
        },
        "slide_3": {
          "type": "slide",
          "settings": {
            "media_style": "image",
            "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_42_26_AM.png",
            "video_url": "",
            "controls": False,
            "stars_count": 5,
            "text": "<p>\"I was sceptical — supplements often disappoint me. But I stayed consistent for the full 60 days and the difference is real. The burning discomfort in my legs has genuinely calmed, and I feel like I’m moving more freely day to day. Solid product.\"</p>",
            "author": "<p><strong>Alan M.</strong> — Age 61, Verified Customer</p>"
          }
        },
        "slide_4": {
          "type": "slide",
          "settings": {
            "media_style": "image",
            "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_38_09_AM.png",
            "video_url": "",
            "controls": False,
            "stars_count": 5,
            "text": "<p>\"I researched ALA carefully before buying — the R-form mattered to me, not just the cheap racemic mix. After about a month I noticed the sensitivity in my feet easing off, and by month two I was genuinely more comfortable walking and standing. Very happy with this.\"</p>",
            "author": "<p><strong>Thomas R.</strong> — Age 59, Verified Customer</p>"
          }
        }
      },
      "block_order": [
        "slide_1",
        "slide_2",
        "slide_3",
        "slide_4"
      ],
      "name": "SS - Testimonials #12",
      "settings": {
        "heading": "<h1><strong>What Real Customers Are Saying</strong></h1>",
        "heading_custom": False,
        "heading_font": "josefin_sans_n4",
        "heading_size": 30,
        "heading_size_mobile": 24,
        "heading_height": 130,
        "heading_align": "center",
        "heading_align_mobile": "center",
        "sub_heading": "",
        "sub_heading_custom": False,
        "sub_heading_font": "josefin_sans_n4",
        "sub_heading_size": 30,
        "sub_heading_size_mobile": 22,
        "sub_heading_height": 150,
        "sub_heading_mt": 12,
        "sub_heading_align": "center",
        "sub_heading_align_mobile": "center",
        "slider_view": 3.1,
        "slider_view_mobile": 1.2,
        "slider_gap": 28,
        "slider_gap_mobile": 20,
        "slider_mt": 20,
        "autoplay": False,
        "autoplay_delay": 5,
        "card_padding_vertical": 20,
        "card_padding_vertical_mobile": 16,
        "card_padding_horizontal": 20,
        "card_padding_horizontal_mobile": 16,
        "card_radius": 20,
        "card_border_thickness": 1,
        "card_shadow": False,
        "media_radius": 20,
        "media_border_thickness": 0,
        "media_ratio": "square",
        "media_ratio_mobile": "square",
        "content_padding_vertical": 0,
        "content_padding_vertical_mobile": 0,
        "content_padding_horizontal": 0,
        "content_padding_horizontal_mobile": 0,
        "hide_content": False,
        "stars_size": 16,
        "stars_mt": 12,
        "stars_align": "center",
        "stars_align_mobile": "center",
        "text_custom": False,
        "text_font": "josefin_sans_n4",
        "text_size": 16,
        "text_size_mobile": 16,
        "text_height": 130,
        "text_mt": 12,
        "text_align": "center",
        "text_align_mobile": "center",
        "author_custom": False,
        "author_font": "josefin_sans_n4",
        "author_size": 14,
        "author_size_mobile": 14,
        "author_height": 130,
        "author_mt": 12,
        "author_align": "center",
        "author_align_mobile": "center",
        "navigation_mt": 40,
        "navigation_gap": 20,
        "navigation_align": "center",
        "navigation_align_mobile": "center",
        "arrow_size": 50,
        "arrow_size_mobile": 50,
        "arrow_show_desktop": True,
        "arrow_show_mobile": True,
        "dots_size": 10,
        "dots_size_mobile": 10,
        "dots_show_desktop": False,
        "dots_show_mobile": True,
        "btn_icon_size": 50,
        "btn_icon_size_mobile": 40,
        "card_bg_color": "#ffffff",
        "card_bg_gradient": "",
        "card_border_color": "#dedbc4",
        "media_border_color": "#121212",
        "stars_color": "#323232",
        "text_color": "#323232",
        "author_color": "#323232",
        "video_icon_bg_color": "#ffffff",
        "video_icon_color": "#121212",
        "arrow_color": "#837c5c",
        "arrow_hover_color": "#837c5c",
        "dots_color": "#837c5c",
        "heading_color": "#000000",
        "sub_heading_color": "#837c5c",
        "background_color": "#f6f5f2",
        "background_gradient": "",
        "border_color": "#121212",
        "margin_top": 0,
        "margin_bottom": 0,
        "padding_top": 36,
        "padding_bottom": 36,
        "padding_horizontal": 5,
        "padding_horizontal_mobile": 1.5,
        "full_width": True,
        "content_width": 1200,
        "border_thickness": 0,
        "lazy": True
      }
    },
    "ss_video_with_text_3_NtTTXB": {
      "type": "ss-video-with-text-3",
      "name": "SS - Video with Text #3",
      "settings": {
        "media": "image",
        "image": "shopify://shop_images/ChatGPT_Image_May_12_2026_12_44_53_AM.png",
        "video_url": "",
        "media_width": 50,
        "media_width_mobile": 100,
        "media_position": "first",
        "media_position_mobile": "first",
        "media_ratio": "original",
        "media_ratio_mobile": "original",
        "media_border_thickness": 0,
        "media_radius": 0,
        "controls": False,
        "autoplay": True,
        "loop": True,
        "content_padding_vertical": 32,
        "content_padding_vertical_mobile": 40,
        "content_padding_horizontal": 50,
        "content_padding_horizontal_mobile": 12,
        "heading": "<h2><strong>What Sets Romira R-ALA Apart?</strong></h2>",
        "heading_custom": False,
        "heading_font": "josefin_sans_n4",
        "heading_size": 50,
        "heading_size_mobile": 36,
        "heading_height": 110,
        "heading_align": "left",
        "heading_align_mobile": "center",
        "heading_position": "1",
        "heading_position_mobile": "1",
        "sub_heading": "",
        "sub_heading_custom": False,
        "sub_heading_font": "josefin_sans_n4",
        "sub_heading_size": 18,
        "sub_heading_size_mobile": 18,
        "sub_heading_height": 150,
        "sub_heading_align": "left",
        "sub_heading_align_mobile": "center",
        "sub_heading_mt": 40,
        "sub_heading_position": "2",
        "sub_heading_position_mobile": "4",
        "text": "<p>✅ <strong>Pure R-Form — Not a Cheap Racemic Mix</strong></p><p>Standard ALA is a 50/50 mixture of R and S forms. The S-form is synthetic and not found in nature. Romira uses only the pure R-form — the version your body is designed to recognize and work with.</p><p>✅ <strong>600mg — The Recognized Daily Serving</strong></p><p>The most widely used daily serving for nerve comfort and antioxidant support in clinical and wellness settings. A transparent, meaningful dose — not padded with fillers or hidden in a proprietary blend.</p><p>✅ <strong>Organic Coconut Oil for Absorption</strong></p><p>R-ALA is fat-soluble. Pairing it with Organic Coconut Oil in every capsule supports proper absorption — so the dose you take is the dose your body actually uses.</p><p>✅ <strong>Universal Antioxidant — Water and Fat Soluble</strong></p><p>Works inside and outside cells. Regenerates Vitamin C, Vitamin E, and Glutathione. No other single antioxidant covers as much cellular ground.</p>",
        "text_custom": False,
        "text_font": "josefin_sans_n4",
        "text_size": 18,
        "text_size_mobile": 18,
        "text_height": 150,
        "text_align": "left",
        "text_align_mobile": "left",
        "text_mt": 40,
        "text_position": "2",
        "text_position_mobile": "4",
        "button": "",
        "button_url": "",
        "button_custom": False,
        "button_font": "josefin_sans_n4",
        "button_size": 18,
        "button_size_mobile": 18,
        "button_height": 100,
        "button_align": "left",
        "button_align_mobile": "center",
        "button_mt": 32,
        "button_padding_vertical": 16,
        "button_padding_vertical_mobile": 16,
        "button_padding_horizontal": 26,
        "button_padding_horizontal_mobile": 26,
        "button_radius": 32,
        "button_border_thickness": 0,
        "button_use_arrow": True,
        "button_position": "4",
        "button_position_mobile": "3",
        "button_color": "#ffffff",
        "button_hover_color": "#ffffff",
        "button_bg_color": "#264165",
        "button_bg_hover_color": "#1a2e47",
        "button_border_color": "#000000",
        "button_border_hover_color": "#000000",
        "media_border_color": "#000000",
        "heading_color": "#000000",
        "sub_heading_color": "#000000",
        "text_color": "#000000",
        "background_color": "#ffffff",
        "background_gradient": "",
        "border_color": "#000000",
        "margin_top": 0,
        "margin_bottom": 0,
        "padding_top": 36,
        "padding_bottom": 36,
        "padding_horizontal": 0,
        "padding_horizontal_mobile": 0,
        "full_width": True,
        "content_width": 120,
        "border_thickness": 0,
        "lazy": True
      }
    },
    "icon_bar_ebx4KY": {
      "type": "icon-bar",
      "blocks": {
        "column_z7dXJB": {
          "type": "column",
          "settings": {
            "icon": "pill",
            "filled_icon": False,
            "title": "Take 2 Capsules Daily",
            "text": ""
          }
        },
        "column_QAqjxk": {
          "type": "column",
          "settings": {
            "icon": "restaurant",
            "filled_icon": True,
            "title": "Take With a Meal",
            "text": ""
          }
        },
        "column_Tj8amX": {
          "type": "column",
          "settings": {
            "icon": "schedule",
            "filled_icon": False,
            "title": "Morning Or Evening",
            "text": ""
          }
        },
        "column_Thj8Ah": {
          "type": "column",
          "settings": {
            "icon": "sync",
            "filled_icon": False,
            "title": "Stay Consistent For 60 Days",
            "text": ""
          }
        }
      },
      "block_order": [
        "column_z7dXJB",
        "column_QAqjxk",
        "column_Tj8amX",
        "column_Thj8Ah"
      ],
      "name": "Icon Bar",
      "settings": {
        "display_id": False,
        "visibility": "always-display",
        "title": "",
        "title_highlight_color": "#000000",
        "heading_size": "h1",
        "text": "<h1>How To Use Romira R-Alpha Lipoic Acid</h1>",
        "color_scheme": "custom",
        "icon_layout": "vertical",
        "icon_size": "large",
        "icon_color": "accent-1",
        "cards_color_scheme": "background-1",
        "type": "slide",
        "autoplay": False,
        "autoplay_speed": 4,
        "arrows_color_scheme": "background-2",
        "transparent_arrows": True,
        "dots_color_scheme": "accent-1",
        "desktop_full_page": False,
        "columns_desktop": 4,
        "slider_desktop": False,
        "per_move_desktop": 1,
        "desktop_spacing": 32,
        "desktop_side_padding": 0,
        "desktop_padding_calc": True,
        "desktop_adaptive_height": True,
        "desktop_dots_position": "under",
        "desktop_arrows_position": "sides",
        "columns_mobile": "1",
        "slider_mobile": True,
        "enable_mobile_preview": False,
        "mobile_adaptive_height": True,
        "mobile_dots_position": "hidden",
        "mobile_arrows_position": "under",
        "padding_top": 12,
        "padding_bottom": 60,
        "custom_colors_background": "#ffffff",
        "custom_gradient_background": "",
        "custom_colors_text": "#000000",
        "custom_cards_colors_background": "#ffffff",
        "custom_cards_gradient_background": "",
        "custom_cards_colors_text": "#000000"
      }
    },
    "ss_video_with_text_3_fTa3mc": {
      "type": "ss-video-with-text-3",
      "name": "SS - Video with Text #3",
      "settings": {
        "media": "image",
        "image": "shopify://shop_images/Untitled_design_66.png",
        "video_url": "",
        "media_width": 50,
        "media_width_mobile": 100,
        "media_position": "second",
        "media_position_mobile": "second",
        "media_ratio": "original",
        "media_ratio_mobile": "original",
        "media_border_thickness": 0,
        "media_radius": 0,
        "controls": False,
        "autoplay": True,
        "loop": True,
        "content_padding_vertical": 32,
        "content_padding_vertical_mobile": 40,
        "content_padding_horizontal": 100,
        "content_padding_horizontal_mobile": 12,
        "heading": "<h2>Why Choose Romira?</h2>",
        "heading_custom": False,
        "heading_font": "josefin_sans_n4",
        "heading_size": 50,
        "heading_size_mobile": 40,
        "heading_height": 110,
        "heading_align": "left",
        "heading_align_mobile": "center",
        "heading_position": "1",
        "heading_position_mobile": "1",
        "sub_heading": "<h3>You have probably already tried things that did not work. You deserve a brand that takes your nerve health seriously — and gives you the right form, the right dose, and the right support.</h3>",
        "sub_heading_custom": False,
        "sub_heading_font": "josefin_sans_n4",
        "sub_heading_size": 18,
        "sub_heading_size_mobile": 18,
        "sub_heading_height": 150,
        "sub_heading_align": "left",
        "sub_heading_align_mobile": "center",
        "sub_heading_mt": 16,
        "sub_heading_position": "2",
        "sub_heading_position_mobile": "2",
        "text": "<p>✅ <strong>Made in the USA — GMP Certified</strong><br/>Every batch produced in a certified facility with full quality controls in place.</p><p>✅ <strong>Third-Party Lab Tested</strong><br/>Independently verified for purity, potency, and consistency — no guessing what is actually in the capsule.</p><p>✅ <strong>Pure R-Form ALA with Organic Coconut Oil</strong><br/>The naturally active form, paired with Organic Coconut Oil for absorption. Not a cheap racemic mix, not padded with fillers.</p><p>✅ <strong>60-Day Money-Back Guarantee</strong><br/>Give it 60 days of consistent daily use — or your money back, no questions asked.</p>",
        "text_custom": False,
        "text_font": "josefin_sans_n4",
        "text_size": 18,
        "text_size_mobile": 18,
        "text_height": 150,
        "text_align": "left",
        "text_align_mobile": "left",
        "text_mt": 40,
        "text_position": "3",
        "text_position_mobile": "4",
        "button": "",
        "button_url": "",
        "button_custom": False,
        "button_font": "josefin_sans_n4",
        "button_size": 18,
        "button_size_mobile": 18,
        "button_height": 100,
        "button_align": "left",
        "button_align_mobile": "center",
        "button_mt": 32,
        "button_padding_vertical": 16,
        "button_padding_vertical_mobile": 16,
        "button_padding_horizontal": 26,
        "button_padding_horizontal_mobile": 26,
        "button_radius": 32,
        "button_border_thickness": 0,
        "button_use_arrow": True,
        "button_position": "4",
        "button_position_mobile": "3",
        "button_color": "#ffffff",
        "button_hover_color": "#ffffff",
        "button_bg_color": "#264165",
        "button_bg_hover_color": "#1a2e47",
        "button_border_color": "#000000",
        "button_border_hover_color": "#000000",
        "media_border_color": "#000000",
        "heading_color": "#000000",
        "sub_heading_color": "#000000",
        "text_color": "#000000",
        "background_color": "#f6f5f1",
        "background_gradient": "",
        "border_color": "#000000",
        "margin_top": 0,
        "margin_bottom": 0,
        "padding_top": 60,
        "padding_bottom": 60,
        "padding_horizontal": 0,
        "padding_horizontal_mobile": 0,
        "full_width": True,
        "content_width": 100,
        "border_thickness": 0,
        "lazy": True
      }
    },
    "results_7448bX": {
      "type": "results",
      "blocks": {
        "row_LVXpfM": {
          "type": "row",
          "settings": {
            "percentage": 71,
            "row_text": "<p><strong>71% of participants in published alpha-lipoic acid nerve comfort research reported meaningful reductions in tingling, burning, and sensitivity with consistent daily supplementation</strong></p>"
          }
        },
        "row_HqrFjp": {
          "type": "row",
          "settings": {
            "percentage": 88,
            "row_text": "<p><strong>R-ALA’s dual water and fat solubility allows antioxidant protection across more cellular environments than virtually any other known antioxidant — making it uniquely effective for nerve tissue</strong></p>"
          }
        },
        "row_76XHzi": {
          "type": "row",
          "settings": {
            "percentage": 92,
            "row_text": "<p><strong>92% of Romira R-ALA customers report noticeable improvements in daily nerve comfort, reduced sensitivity, and overall wellness with consistent use</strong></p>"
          }
        }
      },
      "block_order": [
        "row_LVXpfM",
        "row_HqrFjp",
        "row_76XHzi"
      ],
      "settings": {
        "display_id": False,
        "visibility": "always-display",
        "title": "<strong>What The Research &amp; Our Customers Show</strong>",
        "title_highlight_color": "#000000",
        "heading_size": "h1",
        "text": "",
        "video_muted_autoplay": True,
        "color_scheme": "custom",
        "layout": "results_second",
        "results_headline": "",
        "results_title_highlight_color": "#264165",
        "results_headline_size": "h2",
        "results_text": "",
        "results_headline_alignment": "center",
        "caption": "<p>Based on peer-reviewed clinical research and published literature on alpha-lipoic acid.</p>",
        "button_label": "",
        "link": "",
        "button_style_secondary": False,
        "atc_button_label": "",
        "atc_product": "",
        "atc_skip_cart": False,
        "padding_top": 36,
        "padding_bottom": 36,
        "custom_colors_background": "#f6f5f1",
        "custom_gradient_background": "",
        "custom_colors_text": "#2e2a39",
        "custom_colors_accent": "#264165",
        "custom_colors_solid_button_background": "#264165",
        "custom_colors_solid_button_text": "#ffffff",
        "custom_colors_outline_button": "#264165"
      }
    },
    "faq_section_pea": {
      "type": "collapsible-content",
      "blocks": {
        "faq_q1": {
          "type": "collapsible_row",
          "settings": {
            "heading": "How long until I see results?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>R-ALA works cumulatively — it supports the underlying systems connected to nerve health rather than providing instant relief. Most people begin to notice improvements in nerve comfort between weeks 3 and 6. Nighttime tingling and burning are often the first things to ease. Give it the full 60 days for the best evaluation.</p>",
            "page": ""
          }
        },
        "faq_q2": {
          "type": "collapsible_row",
          "settings": {
            "heading": "What is R-Alpha Lipoic Acid?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>Alpha-lipoic acid (ALA) is a naturally occurring antioxidant compound found in every cell of the body. It plays a key role in energy production inside the mitochondria. R-Alpha Lipoic Acid is the naturally occurring, biologically active form of ALA — the enantiomer your body produces and recognizes. It is both water- and fat-soluble, making it one of the most versatile antioxidants known.</p>",
            "page": ""
          }
        },
        "faq_q3": {
          "type": "collapsible_row",
          "settings": {
            "heading": "Why is the R-form better than regular ALA?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>Standard alpha-lipoic acid supplements typically contain a 50/50 mixture of R-ALA and S-ALA — called a racemic mixture. The S-form is synthetic and does not occur naturally in the body. The R-form is the naturally occurring enantiomer — the one your body produces, recognizes, and uses most efficiently. For people who want a more targeted, premium approach, pure R-ALA is the preferred choice.</p>",
            "page": ""
          }
        },
        "faq_q4": {
          "type": "collapsible_row",
          "settings": {
            "heading": "Why is Coconut Oil included?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>R-Alpha Lipoic Acid is fat-soluble, which means it is absorbed more efficiently when taken alongside a source of healthy fat. Each Romira R-ALA capsule includes Organic Coconut Oil to support this absorption — ensuring the 600mg dose you take is the dose your body can actually use. You can also take your capsules with a meal that contains some healthy fat for the same benefit.</p>",
            "page": ""
          }
        },
        "faq_q5": {
          "type": "collapsible_row",
          "settings": {
            "heading": "Are there any side effects?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>R-ALA is generally well tolerated. A small number of users report mild nausea, which can usually be avoided by taking capsules with food. If you are managing blood sugar levels or taking diabetes medication, consult your healthcare provider before use — as ALA supports glucose metabolism. If you have any underlying health conditions or take prescription medication, check with your doctor before starting.</p>",
            "page": ""
          }
        },
        "faq_q6": {
          "type": "collapsible_row",
          "settings": {
            "heading": "Can I take it with other supplements or medications?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>R-ALA is generally considered safe alongside most supplements. It actually supports the regeneration of other antioxidants including Vitamin C, Vitamin E, and Glutathione, making it a natural complement to a broader wellness routine. If you are taking prescription medication — particularly for blood sugar, inflammation, or neurological conditions — consult your healthcare provider before use.</p>",
            "page": ""
          }
        },
        "faq_q7": {
          "type": "collapsible_row",
          "settings": {
            "heading": "What does 'universal antioxidant' mean?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>Most antioxidants are either water-soluble (like Vitamin C) or fat-soluble (like Vitamin E) — which limits where in the body they can work. R-ALA is both water- and fat-soluble, meaning it can provide antioxidant protection inside cells, outside cells, and around cell membranes. This is why it is sometimes called a universal antioxidant and why it is especially valuable for nerve tissue, which requires protection in multiple cellular environments.</p>",
            "page": ""
          }
        },
        "faq_q8": {
          "type": "collapsible_row",
          "settings": {
            "heading": "What makes Romira R-ALA different from other brands?",
            "icon": "",
            "filled_icon": False,
            "row_content": "<p>Three things set Romira apart: the form, the absorption support, and the guarantee. We use the pure R-form — not a cheap racemic mix. We include Organic Coconut Oil in every capsule to support fat-soluble absorption. And we back everything with a 60-day money-back guarantee because we want you to have the full evaluation window. Made in the USA in a GMP-certified facility, third-party tested for purity and potency.</p>",
            "page": ""
          }
        }
      },
      "block_order": [
        "faq_q1",
        "faq_q2",
        "faq_q3",
        "faq_q4",
        "faq_q5",
        "faq_q6",
        "faq_q7",
        "faq_q8"
      ],
      "settings": {
        "display_id": False,
        "visibility": "always-display",
        "caption": "",
        "title": "Frequently Asked Questions",
        "title_highlight_color": "#6d388b",
        "heading_size": "h1",
        "heading_alignment": "center",
        "layout": "none",
        "color_scheme": "background-1",
        "container_color_scheme": "background-2",
        "open_first_collapsible_row": False,
        "video_muted_autoplay": True,
        "image_ratio": "adapt",
        "desktop_layout": "image_second",
        "row_heading_size": "medium",
        "collapse_icon": "carret",
        "display_top_border": True,
        "padding_top": 60,
        "padding_bottom": 60,
        "custom_colors_background": "#ffffff",
        "custom_gradient_background": "",
        "custom_colors_text": "#2e2a39",
        "custom_contaner_colors_background": "#ffffff",
        "custom_container_gradient_background": "",
        "custom_contaner_colors_text": "#2e2a39"
      }
    },
    "177005298524a79f37": {
      "type": "apps",
      "settings": {
        "display_id": False,
        "include_margins": True
      }
    },
    "b321ab88-2b59-4dba-bade-54885c874ca5": {
      "type": "section-divider",
      "settings": {
        "visibility": "always-display",
        "shape": "waves_3",
        "flip_horizontal": False,
        "flip_vertical": False,
        "shape_color": "accent-1",
        "custom_shape_color": "#264165",
        "background_color": "background-1",
        "custom_background_color": "#ffffff",
        "padding_top": 0,
        "padding_bottom": 0
      }
    }
  },
  "order": [
    "main",
    "related-products",
    "ss_video_with_text_3_qiaRVV",
    "ss_testimonial_12_aKxHaF",
    "ss_video_with_text_3_NtTTXB",
    "icon_bar_ebx4KY",
    "ss_video_with_text_3_fTa3mc",
    "results_7448bX",
    "faq_section_pea",
    "177005298524a79f37",
    "b321ab88-2b59-4dba-bade-54885c874ca5"
  ]
}

# Serialize the template to JSON
template_str = json.dumps(template, ensure_ascii=False)

# Build the GraphQL mutation with the content escaped for a GraphQL string literal
escaped = template_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')

mutation = f'''mutation {{
  themeFilesUpsert(
    themeId: "{THEME_ID}",
    files: [{{
      filename: "templates/product.lipoic.json",
      body: {{
        type: TEXT,
        value: "{escaped}"
      }}
    }}]
  ) {{
    upsertedThemeFiles {{
      filename
    }}
    userErrors {{
      filename
      message
    }}
  }}
}}'''

# Write the mutation to a temp file
mutation_file = r"C:\Users\Darin Game\AppData\Local\Temp\lipoic_mutation.graphql"
with open(mutation_file, "w", encoding="utf-8") as f:
    f.write(mutation)

print(f"Mutation file written to {mutation_file}")
print(f"Template size: {len(template_str)} chars")

# Run the shopify store execute command
result = subprocess.run(
    f'shopify store execute --store {STORE} --allow-mutations --query-file "{mutation_file}"',
    capture_output=True, text=True, encoding="utf-8", shell=True
)

print("STDOUT:", result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout)
if result.stderr:
    print("STDERR:", result.stderr[-1000:])
print("Return code:", result.returncode)
